# Note: This template uses Docker containers only for development purposes. On production it uses a PostgreSQL database (personal preference).
version: '3.8'
name: TEMPLATE-dev

services:

  # PostgreSQL Database
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - '${DB_PORT}:27017'
    volumes:
      - ./database/seed:/seed
      - ./database/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - shared

  # PostgreSQL Adminer
  adminer:
      image: adminer
      container_name: adminer
      restart: unless-stopped
      ports:
      - '${ADMINER_PORT}:8080'
      networks:
      - shared

networks:
  shared:
